### ISSUE TITLE
Smá vesen

### ISSUE THREAD

**Issue by Oliprik** [JanusG/VLN1-hopur18#1]
Við erum ekki ennþá komnir með neinn kóða.

**Comment by audunnhrafn** [comment]
ekki nógu góður kóði

**Comment by audunnhrafn** [comment]
- 

- [ ] 1.

**Comment by audunnhrafn** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]
